lista =[1,2,3,4,5,6,7,8,9]
print(lista)
elemento = input('ingrese el valor a agregar a la lista: ')
lista.append(int(elemento))
print(lista)
elemento1 = input('ingrese el valor a eliminar a la lista: ')
lista.remove(float(elemento1))
print(lista)
lista.extend([11,12,13,14,15])
print(lista)
lista.insert(1,'nuevo')
print (lista)
elemento1=lista.pop()
print(lista)